name: Pull Requests

on:
  pull_request_target:
    types: [opened]

jobs:
  uneditable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run pull request-related job
        run: |
          # Your job steps related to pull requests